### ISSUE TITLE
Zoho Book Conflicts with python3

### ISSUE THREAD

**Issue by MishalJasmine** [zoho/books-python-wrappers#4]
I am trying to use the zoho books with python3. But there are lot of conflicts. Tired resolving a few but looks like its endless. Can I have python wrappers compatible with python3 also?

**Comment by tloebhard** [comment]
Did you check https://github.com/deepubansal/books-python-wrappers ?

**Comment by MishalJasmine** [comment]
I used the GitHub repo that you suggested. But I am getting this error.

`import os,sys
sys.path.append('./books')
from config import *
from books.model.Organization import Organization
from books.model.Address import Address
from books.api.OrganizationsApi import OrganizationsApi
from books.service.ZohoBooks import ZohoBooks

organizations_api = OrganizationsApi("auth_token", "org_id")
print (organizations_api.get("org_id"))
`

Error:

`URL: https://books.zoho.in/api/v3/organizations/60009660202?organization_id=org_id
Traceback (most recent call last):
  File "test_zoho.py", line 19, in <module>
    main()
  File "test_zoho.py", line 15, in main
    print (organizations_api.get("60009660202"))
  File "/home/dell/xyz/testing/zoho_books/books/api/OrganizationsApi.py", line 55, in get
    resp = zoho_http_client.get(url, self.details) 
  File "/home/dell/xyz/testing/zoho_books/books/util/ZohoHttpClient.py", line 36, in get
    resp, content = http.request(url, 'GET', headers=headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1313, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1063, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 986, in _conn_request
    conn.connect()
  File "/usr/lib/python3.7/http/client.py", line 1422, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1076)
`

**Comment by MishalJasmine** [comment]
I had got this error while using this repo also
